name: "Config updater"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - run: npm start
    
      - name: Update Config
        uses: test-room-7/action-update-file@v1
        with:
            file-path: config.json
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
