name: "Check and Update"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup git environment
        run: |
         git config --global user.email "contact.reallyfatyoshi@gmail.com" 
         git config --global user.name "Workflow"
      
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.17.0

      - name: Install Packages & Run Script
        run: npm i && node index.js

      - name: Git Push
        run: |
          git add --all
          git commit -m "Configuration Update"
          git push
